name = "StandardizedPredictors"
uuid = "5064a6a7-f8c2-40e2-8bdc-797ec6f1ae18"
authors = "Beacon Biosignals, Inc."
version = "1.0.1"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[compat]
Aqua = "0.8"
Statistics = "1"
StatsBase = "0.33, 0.34"
StatsModels = "0.7"
Test = "1"
TestSetExtensions = "3"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[targets]
test = ["Aqua", "Test", "TestSetExtensions"]
